version: '3.3'

services:
  db:
    image: mongo:5.0
    ports:
      - 27017:27017
      - 28017:28017
    container_name: db
  webserver:
    image: webserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 5142:80
      - 7199:443
    container_name: webserver
    depends_on:
      - db