version: '3.3'

services:
  db:
    image: faurby/db
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=f88fa811-92c6-47b5-885b-15769f06fda3
    ports:
      - 27017:27017
      - 28017:28017
    container_name: db
  webserver:
    image: faurby/webserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 5142:80
      - 7199:443
    container_name: webserver
    depends_on:
      - db