version: '3.3'

services:
  db:
    image: mongo:5.0
    ports:
      - 27017:27017
      - 28017:28017
    container_name: db
  server:
    image: server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5077:80
      - 7207:443
    container_name: webserver
    depends_on:
      - db