---
version: "3.6"

networks: 
    blackops-network:
      external: true

volumes:
  grafana-storage:

services:
  webserver:
    image: faurby/webserver:latest
    build:
      context: .
      dockerfile: ./Dockerfile-webserver
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    deploy:
      replicas: 2
      update_config:
        delay: 10s
    ports:
      - 5142:80
      - 7199:443
    container_name: webserver
    depends_on:
      - prometheus
      - grafana
    networks:
      - blackops-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - blackops-network

  grafana:
    image: grafana/grafana:8.4.0
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - blackops-network