---
version: "3.6"

networks:
  monitoring:
  elk:

volumes:
  elk_elasticsearch_data:
  grafana-storage:
  mongo-storage:

services:
  db:
    image: faurby/db
    volumes:
      - mongo-storage:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=f88fa811-92c6-47b5-885b-15769f06fda3
    ports:
      - 27017:27017
      - 28017:28017
    container_name: db
    depends_on:
      - prometheus
      - grafana
    networks:
      - monitoring

  webserver:
    image: faurby/webserver
    build:
      context: .
      dockerfile: ./Dockerfile-webserver
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 5142:80
      - 7199:443
    container_name: webserver
    depends_on:
      - db
      - prometheus
      - grafana
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:8.4.0
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.1"
    environment:
      - "discovery.type=single-node"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1g
    volumes:
      - elk_elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elk

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.17.1"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1g
    environment:
        elasticsearch.hosts: '["http://elasticsearch:9200"]'
    networks:
        - elk

  filebeat:
    image: "docker.elastic.co/beats/filebeat:7.17.1"
    environment:
        - "ELK_USER=${ELK_USER}"
    user: root
    volumes:
        - ${ELK_DIR}/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
        - /var/lib/docker:/var/lib/docker:ro
        - /var/run/docker.sock:/var/run/docker.sock
    networks:
        - elk

  nginx:
    image: nginx
    ports:
      - 9200:9200
      - 5601:5601
      - 8881:8881
      - 8882:8882
    networks:
      - elk
    volumes:
      - type: bind
        source: ${ELK_DIR}/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ${ELK_DIR}/.htpasswd
        target: /etc/nginx/.htpasswd