---
version: "3.6"

networks:
  monitoring:

services:
  db:
    image: faurby/db
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=f88fa811-92c6-47b5-885b-15769f06fda3
    ports:
      - 27017:27017
      - 28017:28017
    container_name: db
    depends_on:
      - prometheus
      - grafana
    networks:
      - monitoring

  webserver:
    image: faurby/webserver
    build:
      context: .
      dockerfile: ./Dockerfile-webserver
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 5142:80
      - 7199:443
    container_name: webserver
    depends_on:
      - db
      - prometheus
      - grafana
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:8.4.0
    ports:
      - "3000:3000"
    networks:
      - monitoring

volumes:
  grafana-storage:
