version: '3.3'

services:
  db:
    image: mongo:5.0
    ports:
      - 27017:27017
      - 28017:28017
    container_name: db
  server:
    image: server
    build:
      context: .
      dockerfile: ./Dockerfile
    # environment:
    #   ASPNETCORE_URLS: https://+;http://+
    #   ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    #   ASPNETCORE_Kestrel__Certificates__Default__Password: 1234
    #   ASPNETCORE_HTTPS_PORT:
    ports:
      - 5077:80
      - 7207:443
    container_name: webserver
    depends_on:
      - db
    # volumes:
    #   - C:/Users/daxzt/.aspnet/https:/https/