# https://texdoc.org/serve/latexmk.pdf/0
# using: https://github.com/xu-cheng/latex-action
# using: https://github.com/actions-js/push 
name: Compile Latex and Release PDF  

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with: 
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will fail to push 
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          run: |
            cd ./report
            pdflatex -output-directory build main.tex 

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'main'
          message: 'publish report.pdf'
          force: 'true' #Ignores push constraints on main branch
          directory: ./report
          author_email: cafm@itu.dk