on:
  push:
    branches:
      - main
  schedule: 
    - cron: "*/5 * * * *"
  

name: Create Release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
        
      - name: 'Get Previous tag'
        id: previoustag
        run: | 
          git fetch -t 
          TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          if [ -z "$TAG" ] 
          then 
            exit 1
          else 
            echo "Tag Found: $TAG"
            echo ::set-output name=tag::$TAG
          fi
          
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
          
      - name: "Build Changelog"
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Minor Release
        if: ${{ github.event_name == 'push'}}
        id: create_minor_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with: 
          tag_name: v${{ steps.semvers.outputs.minor }}
          release_name: Release ${{ steps.semvers.outputs.minor }}
          body: |
            Minor release
            ${{steps.github_release.outputs.changelog}}
          draft: false
          prerelease: false
          
      - name: Create Major Release
        if: ${{ github.event_name == 'schedule'}}
        id: create_major_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with: 
          tag_name: v${{ steps.semvers.outputs.major }}
          release_name: Release ${{ steps.semvers.outputs.major }}
          body: |
            Major release
            ${{steps.github_release.outputs.changelog}}
          draft: false
          prerelease: false
