---
name: Create Release

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  schedule:
    - cron: "0 18 * * 0"    # Runs at 19:00 every Sunday every week

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # Required due to the way Git works. Without it, tags cannot be found

      - name: 'Get Previous tag'
        id: previoustag
        run: |
          git fetch -t -f
          TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          if [ -z "$TAG" ]
          then
            exit 1
          else
            echo "Tag Found: $TAG"
            echo ::set-output name=tag::$TAG
          fi

      - name: 'Get next version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v3.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Minor Release
        if: ${{ github.event_name == 'push'}}
        id: create_minor_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # This token is provided by Actions,
          # you do not need to create your own token
        with:
          tag_name: v${{ steps.semvers.outputs.minor }}
          release_name: Release ${{ steps.semvers.outputs.minor }}
          body: |
            Minor release
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Create Major Release
        if: ${{ github.event_name == 'schedule'}}
        id: create_major_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # This token is provided by Actions,
          # you do not need to create your own token
        with:
          tag_name: v${{ steps.semvers.outputs.major }}
          release_name: Release ${{ steps.semvers.outputs.major }}
          body: |
            Major release
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
