name: Deploy changes

on:
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout this branch
      - uses: actions/checkout@v2
      # Log into docker hub
      - name: Log into dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      # Build webserver image
      - name: build webserver image
        run: docker build -t faurby/webserver -f Dockerfile-webserver .
      # Build database image
      - name: build database image
        run: docker build -t faurby/db -f Dockerfile-db .
      # webserver - Snyk docker scan
      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: faurby/webserver
          args: --file=Dockerfile-webserver
      - name: Upload webserver result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
      # db - Snyk docker scan
      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: faurby/db
          args: --file=Dockerfile-db
      - name: Upload db result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif