---
name: yamllint

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install yamllint
        run: sudo apt-get install yamllint

      - name: Lint YAML files
        run: yamllint .
